services:
  db:
    container_name: postgres
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hyperbone-server

volumes:
  postgres_data:

networks:
  hyperbone-server: